### ISSUE TITLE
Layout and Style Adjustments (Desktop View)

### ISSUE THREAD

**Issue by Prathyush-KKK** [IEEECS-VIT/pravega-racing#54]
Increase navbar size
Increase the overall size of the navbar for better visibility.
Text is lighter than the original website which reduces visibility
Adjust the text color to match the original website for better readability.
Make the Chancellor's quote bold instead of all of his positions
Only the quote should be bold, while the Chancellor’s positions should remain normal.
Right-align the name and positions
Align the Chancellor’s name and positions to the right for better presentation.
Increase image size in recent activities
Enlarge the images under the "Recent Activities" section for more visual emphasis.
Position of navigate arrows in cars page is dependent on size of the text, so it keeps shifting
Make the navigation arrows static, regardless of the car description's text length.
Add border shadow to images to highlight them
Apply a shadow effect to images throughout the site to give them more focus.
Increase left margin of text in driverless tab
Add more space to the left margin of the text on the Driverless tab for better formatting.
Area around images in Contact Us page is empty. Increase image size
Adjust image size on the Contact Us page to reduce the empty space around images.
Hovering on text in the navbar changes it to black, which is unreadable when the background image itself is black
Change the hover effect for navbar text to a color that remains readable against the background image.
In the cars tab, different car images have different backgrounds. Should have uniform backgrounds
Ensure all car images in the cars tab have a consistent background.
Images are of different sizes in teams tab
Standardize the size of all images on the Teams tab for consistency.
Increase gap between text and images in PR activities tab
Create more space between text and images in the PR Activities tab for clarity.
Increase gap between social media logos in the footer
Add more space between the social media logos in the footer for a cleaner look.
Vertically center align the content in the footer
Adjust the content in the footer so it is vertically centered.
Change font color for submit button hover in footer and add space between button and textbox
Improve the hover effect for the submit button and add spacing between the button and textbox in the footer.

**Comment by jainaryan04** [comment]
navbar and homepage layout fixed
